#!/bin/bash

MY_TOKEN=$(cat "$HOME/var/check_mk/web/automation/automation.secret")

resp=$(wget -qO- --header="Authorization: Bearer $MY_TOKEN" "https://$1:$2/metrics" | grep "$3" | awk '{print $2}')

echo "$resp"

if [ "$resp" -eq "5" ]; then
    exit 0
else
    exit 2
fi
