#!/bin/python3
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse
import socket, select
import struct
import sys
import time
import requests
import json
import htcondor

#Uncomment to enable debugging of condor collector communication
#htcondor.param['TOOL_DEBUG'] = 'D_FULLDEBUG,D_SECURITY'
#htcondor.enable_debug()

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def count_history_jobs(hostname):
    coll = htcondor.Collector("%s:9619" % hostname )
    schedd_ad = coll.locate(htcondor.DaemonTypes.Schedd, hostname)
    schedd = htcondor.Schedd(schedd_ad)
    job_list = list(schedd.history(requirements='JobCurrentStartDate',
                                   projection=["JobFinishedHookDone"],
                                   since="JobFinishedHookDone < %d" % (time.time()-2*86400),
                                   match=1))
    return len(job_list)

def main():
    args = parse_args()
    api_interface="https://gracc.opensciencegrid.org/q"
    index="xrd-stash*"
    query_string = "_count?q=(server_hostname:%s) AND (@timestamp:[now-4d TO now])" % args.hostname
    api_url = api_interface + '/' + index + '/' + query_string
    try:
        state = gracc_index_count(api_url, None)
        sys.exit(state)
    except socket.gaierror as e:
        # Could not resolve hostname => UNKNOWN
        print('Error: %s' % str(e))
        sys.exit(STATE_UNKNOWN)
    except Exception as e:
        # Calling everything else critical:
        # - socket.error   (Network is unreachable)
        # - socket.timeout
        print('Error: %s' % str(e))
        sys.exit(STATE_CRITICAL)

def gracc_index_count(api_url, hostname):
    r = requests.get(api_url)
    data = json.loads(r.text)
    count = data['count']
    perf_data = ' |count=' + str(count)
    #print (data['count'])
    if count > 0:
        print ('GRACC received ' +str(count) +' records')
        state = STATE_OK
    elif count == 0:
        history_count = 0
        if hostname:
            history_count = count_history_jobs(hostname)
        if history_count:
            print ('GRACC received 0 records but there were history ads')
            state = STATE_CRITICAL
        else:
            print ('GRACC received 0 records but there were no history ads')
            state = STATE_OK
    else: 
        print ('Invalid output')
        state = STATE_UNKNOWN
    print (perf_data)
    return state

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('--hostname', dest='hostname', type=str,
                        help='Cache hostname for query')

    return parser.parse_args()

if __name__ == "__main__":
    # Run script as main
    main()
