#!/usr/bin/python3

import argparse
import subprocess
import sys
import time
import xml.etree.ElementTree as ET

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def get_attribs(entry):
    gk = entry.get("gatekeeper").strip()
    gridtype = entry.get("gridtype").strip()
    fqdn = fqdn_from_gatekeeper_and_gridtype(gk, gridtype)
    hosted = is_hosted_fqdn(fqdn) if fqdn else False
    vos = vos_from_entry(entry)
    vos = ",".join("'%s'" % vo.strip() for vo in sorted(vos))

    return gk, gridtype, fqdn, hosted, vos


def get_tree(url):
    process_info = subprocess.run(
            ["curl", "-Ls", "%s" % url],
            stdout=subprocess.PIPE)
    if process_info.returncode:
        print("Failed to download XML status from frontend at %s." % url)
        sys.exit(STATE_CRITICAL)
    return ET.fromstring(process_info.stdout)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("frontend_url", nargs=1, help="URL of the frontend's status XML (typically https://HOSTNAME/vofrontend/monitor/frontend_status.xml)")
    args = parser.parse_args()

    now = time.time()
    frontend_status_tree = get_tree(args.frontend_url[0])
    unixtime = None
    for time_info in frontend_status_tree.findall("./updated/timezone"):
        if time_info.get("name") != "UTC":
            continue
        unixtime = time_info.get("unixtime")
        if not unixtime:
            continue
        try:
            unixtime = int(unixtime)
        except:
            continue
        break

    if unixtime is None:
        print("Frontend status page did not include unix epoch!")
        sys.exit(STATE_CRITICAL)

    age = now - unixtime
    if age > 20 * 60:
        print("Frontend status is more than 20 minutes old | age=%d" % age)
        sys.exit(STATE_CRITICAL)
    elif age > 15 * 60:
        print("Frontend status is more than 15 minutes old | age=%d" % age)
        sys.exit(STATE_WARNING)
    else:
        print("Frontend status is recently updated | age=%d" % age)

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        print('Error (uncaught exception): %s' % str(exc))
        sys.exit(STATE_CRITICAL)
