#!/usr/bin/python3
# encoding=utf8

import argparse
import sys
import re
import urllib.request
import xml.etree.ElementTree as ET

import htcondor2

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def fqdn_from_gatekeeper_and_gridtype(gatekeeper, gridtype):
    if gridtype.startswith("batch"):  # BOSCO: "login@hostname"
        if "@" in gatekeeper:
            return gatekeeper.split("@")[1]
    elif gridtype == "condor":  # Condor-C: "<schedd host[:port]> <cm host[:port]>"
        match = re.match(r"[^: ]+(?:[:]\d+)?\s+([^: ]+)", gatekeeper)
        if match:
            return match.group(1)
    elif gridtype in ["cream", "gt2", "gt5"]:  # CREAM, GRAM: "hostname[:port]/endpoint"
        match = re.match(r"([^:/]+)", gatekeeper)
        if match:
            return match.group(1)
    elif gridtype == "ec2":  # EC2: "SCHEME://HOST[:PORT][/...]"
        match = re.match(r"\w+://([^:/]+)", gatekeeper)
        if match:
            return match.group(1)
    elif gridtype == "nordugrid":  # this one's prety easy :)
        return gatekeeper


def is_hosted_fqdn(fqdn):
    fqdn = str(fqdn)
    return ((fqdn.startswith("hosted-ce") or fqdn.startswith("pearc-ce")) and ( \
        fqdn.endswith(".grid.uchicago.edu") or fqdn.endswith("opensciencegrid.org"))) or \
        fqdn.endswith(".svc.opensciencegrid.org") \


def get_ce_fqdns_from_factory(factory_fqdn):
    entry_info = set()
    htcondor2.param['SEC_DEFAULT_INTEGRITY']='optional'
    coll = htcondor2.Collector(factory_fqdn)
    entries = coll.query(htcondor2.AdTypes.Any, 'MyType=?="glidefactory"', ['GLIDEIN_Gatekeeper', 'GLIDEIN_GridType'])
    for entry in entries:
        if 'GLIDEIN_Gatekeeper' not in entry or 'GLIDEIN_GridType' not in entry:
            continue
        entry_info.add(fqdn_from_gatekeeper_and_gridtype(entry['GLIDEIN_Gatekeeper'], entry['GLIDEIN_GridType']))
    return entry_info

def get_attribs(entry):
    gk = entry.get("gatekeeper").strip()
    gridtype = entry.get("gridtype").strip()
    fqdn = fqdn_from_gatekeeper_and_gridtype(gk, gridtype)
    hosted = is_hosted_fqdn(fqdn) if fqdn else False
    vos = vos_from_entry(entry)
    vos = ",".join("'%s'" % vo.strip() for vo in sorted(vos))

    return gk, gridtype, fqdn, hosted, vos

def get_tree(params):
    resp = urllib.request.urlopen('https://topology.opensciencegrid.org/rgsummary/xml?%s' % params)
    data = resp.read().decode('utf-8')
    return ET.fromstring(data)


def get_ce_resources_with_fqdns_and_services(resourcegroup):
    resources = resourcegroup.findall("./Resources/Resource")
    res_tuples = [
        (res, res.find("./FQDN").text.strip(), res.findall("./Services/Service"))
        for res in resources
        if res.find("./FQDN") is not None and res.find("./Services/Service") is not None
    ]
    for res_tuple in res_tuples:
        if [svc for svc in res_tuple[2] if svc.find("./Name").text.strip() == "CE"]:
            yield res_tuple


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--factory", default="gfactory-2.opensciencegrid.org")
    args = parser.parse_args()

    prod_tree = get_tree("gridtype=on&gridtype_1=on")
    active_topology_ces = set()
    inactive_topology_ces = set()
    for resourcegroup in prod_tree.findall("./ResourceGroup"):
        for resource, fqdn, services in get_ce_resources_with_fqdns_and_services(resourcegroup):
            if resource.find("./Disable") is not None and resource.find("./Disable").text.strip() == "false" and \
                    resource.find("./Active") is not None and resource.find("./Active").text.strip() == "true":
                active_topology_ces.add(fqdn)
            else:
                inactive_topology_ces.add(fqdn)

    factory_ces = set(fqdn for fqdn in get_ce_fqdns_from_factory(args.factory) if is_hosted_fqdn(fqdn))

    inconsistent_ces = factory_ces.difference(active_topology_ces)

    msg = "Factory and topology are consistent for hosted CEs."
    if inconsistent_ces:
        msg = "The following CEs are in the factory but not active in topology: %s" % ", ".join(inconsistent_ces)

    print("%s|count=%d" % (msg, len(inconsistent_ces)))

    if inconsistent_ces:
        sys.exit(STATE_CRITICAL)

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        print("Exception occcurred when running probe: %s" % str(exc))
        sys.exit(STATE_UNKNOWN)
