#!/usr/bin/env python3
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse
import sys
import time
import os

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def main():
    args = parse_args()
    states = [STATE_OK]
    messages = []
    extra_vars = {}
    if args.extra_vars:
        try:
            #parse extra condor configs to overwrite default: 
            #example args from command like: --extra-vars _condor_VAR1=value1;_condor_VAR2=value2
            #parsed to dictionary extra_vars = {'_condor_VAR1' : value1, '_condor_VAR2' : value2}
            extra_vars = dict((k.strip(), v.strip())
                             for k, v in (element.split('=')
                                 for element in args.extra_vars.split(';')))
       # except Exception as e:
        #    states.append(STATE_UNKNOWN)
         #   messages.append(str(e) + " Please review --extra-vars option")
          #  print (messages)
    
            for var in extra_vars.keys():
                if var.startswith('_condor_'):
                    os.environ[var] = str(extra_vars[var])
                    #print (var + os.environ[var])
                else:
                    messages.append("Extra variable not valid, should start with \'_condor_\', ignoring")
        except Exception as e:
            states.append(STATE_UNKNOWN)
            messages.append(str(e) + " Please review --extra-vars option")
            print (messages)


    #import htcondor after os.environ changed
    import htcondor2
    daemon_ads = []
    try:
        coll = htcondor2.Collector(args.collector)
        daemon_ads = coll.query(htcondor2.AdTypes.Any, projection = ['Name'])
    except IOError as e:
        # Connection failed
        states.append(STATE_CRITICAL)
        messages.append(str(e) + " " +args.collector + " failed.")
    except Exception as e:
        # Other error
        states.append(STATE_UNKNOWN)
        messages.append(str(e) + " " + args.collector+ " failed.")

    number_of_daemons = len(daemon_ads)
    if number_of_daemons:
        messages.append(str(number_of_daemons) + " active daemons")
    else:
        messages.append("status unknown")
        states.append(STATE_UNKNOWN)

    state = max(states)
    message = ', '.join(messages)

    perf_data = ' |daemons=%d' % number_of_daemons

    if not message:
        message = 'OK'

    print(message + perf_data)
    sys.exit(state)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--collector', dest='collector', type=str,
                        help='Collector hostname for condor_status -pool')
    parser.add_argument('--extra-vars', dest='extra_vars', type=str, 
                        help='Overwrite variables defined in condor_config_val, seperated by \';\', e.g. _condor_VAR1=value1;_condor_VAR2=value2')
    return parser.parse_args()

if __name__ == "__main__":
    # Run script as main
    main()
