#!/usr/bin/env python
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse
import sys
#import htcondor
import os

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def main():
    args = parse_args()
    states = [STATE_OK]
    messages = []
    jobs = []
    extra_vars = {}
    if args.extra_vars:
        try:
            #parse extra condor configs to overwrite default:
            #example args from command like: --extra-vars _condor_VAR1=value1;_condor_VAR2=value2
            #parsed to dictionary extra_vars = {'_condor_VAR1' : value1, '_condor_VAR2' : value2}
            extra_vars = dict((k.strip(), v.strip())
                             for k, v in (element.split('=')
                                 for element in args.extra_vars.split(';')))

            for var in extra_vars.keys():
                if var.startswith('_condor_'):
                    os.environ[var] = str(extra_vars[var])
                    #print (var + os.environ[var])
                else:
                    messages.append("Extra variable not valid, should start with \'_condor_\', ignoring")
        except Exception as e:
            states.append(STATE_UNKNOWN)
            messages.append(str(e) + " Please review --extra-vars option")
            print (messages)

    #import htcondor after os.environ changed
    import htcondor

    job_attrs = [
        'JobStatus',
        'ServerTime',
        'EnteredCurrentStatus',
        'GridJobStatus',
        'GridJobId',
        'HoldReasonCode',
    ]

    try:
        coll = htcondor.Collector(args.collector)
        schedd_ad = coll.locate(htcondor.DaemonTypes.Schedd, args.schedd)
        #print (schedd_ad)
        schedd = htcondor.Schedd(schedd_ad)
        jobs = schedd.xquery(projection=job_attrs)
    except IOError as e:
        # Connection failed
        states.append(STATE_CRITICAL)
        messages.append(str(e))
    except Exception as e:
        # Other error
        states.append(STATE_UNKNOWN)
        messages.append(str(e))

    #perf_data = ' |running=%(running)d idle=%(idle)d held=%(held)d factory_held=%(factory_held)d' % stats
    #perf_data += ' req_idle=' + str(req_idle)
    #perf_data += ' req_max=' + str(req_max)
   
    state = max(states)
    message = ', '.join(messages) 
    if not message:
        message = 'Scheduler is up.'

    #print(message + perf_data)
    print(message)
    sys.exit(state)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--collector', dest='collector', type=str,
                        help='Collector hostname for condor_q -pool')
    parser.add_argument('--schedd', dest='schedd', type=str,
                        help='Schedd hostname for condor_q -name')
    parser.add_argument('--extra-vars', dest='extra_vars', type=str,
                        help='Overwrite variables defined in condor_config_val, seperated by \';\', e.g. _condor_VAR1=value1;_condor_VAR2=value2')
    return parser.parse_args()

if __name__ == "__main__":
    # Run script as main
    main()
