#!/usr/bin/python3
import os
import sys
import traceback
from XRootD import client

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def xrdread(cache,port,timeout,filet):
    try:
        with client.File() as f:
            status, response = f.open('root://'+cache+':'+str(port)+'//'+filet,timeout=timeout) 
            if(status.error == True):
                return STATE_OK;
            else:
                return STATE_CRITICAL;
           # status, data = f.read(size=4)
           # print(status)

    except Exception as e:
       traceback.print_exc()

try:
    cache = sys.argv[1]
    path="/user/ligo/test_access/access_ligo"
    status_1 = xrdread(cache,8443,500,path)
 
    path="//osgconnect/protected/fandri/access_osg_protected"
    status_2 = xrdread(cache,1094,500,path)

    if(status_1 == STATE_OK and status_2 == STATE_OK):
        sys.exit(STATE_OK);
    else:
        sys.exit(STATE_CRITICAL);

except Exception as e:
    sys.exit(STATE_UNKNOWN)
    traceback.print_exc()
