#!/usr/bin/python3

import argparse
import requests
import json
import sys

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def parse_args():
    parser = argparse.ArgumentParser()
    
    parser.add_argument('--url', dest='url', type=str,
                        help='The url of the status page')
    parser.add_argument('--headers', dest='headers',
                        default='{"accept": "application/json"}',
                        #action='append',
                        help='The headers of the status page. Default value \'{"accept": "application/json"}\'')
    return parser.parse_args()

def main():
    args = parse_args()
    url = args.url
    states = [STATE_OK]
    messages = []
    #headers = {
    #    'accept': 'application/json',
    #}
    headers = json.loads(args.headers)
    try:
        resp = requests.get(url, headers=headers, timeout=10)
        #print (resp.status_code)
        json_page = json.loads(resp.content.decode('ascii'))
        #print (json_page)
        if resp.status_code == 200:
            try:
    	        hub_status = json_page["status"]
    	        messages.append("Hub status: " + hub_status)
    	        if hub_status != 'healthy':
                    messages.append("Hub not healty")
                    states.append(STATE_CRITICAL)
                messages.append("Page content: " + str(json_page)[:1000])
            except KeyError as e:
                messages.append("Error: Key "+ str(e) + " not found in the page")
                messages.append("Page content: " + str(json_page)[:1000])
                states.append(STATE_CRITICAL)
        else:
            messages.append("Page request status code: %d" % resp.status_code)
            messages.append("Page content: " + str(json_page)[:1000])
            states.append(STATE_CRITICAL)

    except requests.RequestException as e:
        messages.append("Failed to request the status page: " + str(e))
        states.append(STATE_CRITICAL)
    state = max(states)
    if state > STATE_OK:
        messages.append("Please verify the url: %s, and headers: %s" % ( url, headers))
    message = '. '.join(messages)
    print(message)
    sys.exit(state)

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print('Error (uncaught exception): %s' % str(e))
        sys.exit(STATE_CRITICAL)
