#!/usr/bin/env python3

from xml.etree.ElementTree import parse
import xml.etree.ElementTree as ET
import os
import urllib
import urllib.request
import re
import sys
import json
import traceback

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def get_ce_resources_with_fqdns_and_services(resourcegroup):
    resources = resourcegroup.findall("./Resources/Resource")
    
    res_tuples = [
        (res, res.find("./FQDN").text.strip(), res.findall("./Services/Service"))
        for res in resources
        if res.find("./FQDN") is not None and res.find("./Services/Service") is not None and res.find("./Services/Service/Name").text.strip() in ["Pelican cache", "XRootD cache server"]
    ]
    for res_tuple in res_tuples:
        if [svc for svc in res_tuple[2]]:
            yield res_tuple

def get_tree(params):
    resp = urllib.request.urlopen('https://topology.opensciencegrid.org/rgsummary/xml?%s' % params)
    data = resp.read().decode('utf-8')
    return ET.fromstring(data)

def get_monitoring_caches(params):

     caches = set();
     url = "http://127.0.0.1:5001/osgmon/check_mk/webapi.py?%s" % params
     response = urllib.request.urlopen(url)
     s = response.read().decode('utf-8')
     data_json = json.loads(s)
     for host in data_json['result']:
         if(data_json['result'][host]['path']=='stash-caches'):
              caches.add(host)
     return caches


def main():
    states = [STATE_OK]
    messages = []

    # topology/services.yaml
    # XRootD cache server: 156
    # Pelican cache: 164
    prod_tree = get_tree("gridtype=on&gridtype_1=on&active=on&active_value=1&service=on&service_156=on&service_164=on")
    topology_caches = set()
    for resourcegroup in prod_tree.findall("./ResourceGroup"):
        for resource, fqdn, services in get_ce_resources_with_fqdns_and_services(resourcegroup):
            topology_caches.add(fqdn)

    OMD_ROOT = os.environ.get('OMD_ROOT')
    secret_filepath = OMD_ROOT + "/var/check_mk/web/automation/automation.secret"
    access = open(secret_filepath,'r')
    secret_line = access.readlines()[0][:-1] #removing trailing '\n'
    action = "action=get_all_hosts"
    password = action + "&_username=automation&_secret="+secret_line
    monitoring_caches = get_monitoring_caches(password)

    topology_diff = topology_caches.difference(monitoring_caches)
    monitoring_diff = monitoring_caches.difference(topology_caches)
    
    if(len(topology_diff) > 0 or len(monitoring_diff)>0):
         states.append(STATE_CRITICAL)
 
    messages.append("Hosts in topology and not in monitoring: ")
    if topology_diff:
    	messages.append(",".join(topology_diff))
    else:
        messages.append("None")
    messages.append(". Hosts in monitoring and not in topology: ")
    if monitoring_diff:
        messages.append(",".join(monitoring_diff))
    else:
        messages.append("None")
    messages.append("\n| topology_diff = %d "% len(topology_diff) + "monitoring_diff = %d \n" % len(monitoring_diff))
    

    print("".join(messages)) 
    sys.exit(max(states))

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        print("Exception occcurred when running probe V1: %s" % str(exc))
        var = traceback.format_exc()
        print(var)
        traceback.print_exception(exc)
        traceback.print_exc()
        sys.exit(STATE_CRITICAL)
