#!/usr/bin/env python3

from urllib.request import urlopen
from xml.etree.ElementTree import parse
import xml.etree.ElementTree as ET
import os
import urllib
import re
import sys
import json

STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def get_ce_resources_with_fqdns_and_services(resourcegroup):
    resources = resourcegroup.findall("./Resources/Resource")
    res_tuples = [
        (res, res.find("./FQDN").text.strip(), res.findall("./Services/Service"))
        for res in resources
        if res.find("./FQDN") is not None and res.find("./Services/Service") is not None
    ]
    for res_tuple in res_tuples:
        if [svc for svc in res_tuple[2]]:
            yield res_tuple

def get_tree(params):
    return ET.fromstring(
        os.popen(
            "curl -Ls 'https://topology.opensciencegrid.org/rgsummary/xml?%s'" %  params 
        ).read()
    )

def is_hosted_fqdn(fqdn):
    return (fqdn.startswith("hosted-") and \
        fqdn.endswith("opensciencegrid.org")) or \
        fqdn.endswith(".svc.opensciencegrid.org") \

def get_monitoring_hosts(params):

     hosts = set();
     url = "http://127.0.0.1:5001/osgmon/check_mk/webapi.py?%s" % params
     response = urlopen(url)
     s = response.read().decode('utf-8')
     data_json = json.loads(s)
     for host in data_json['result']:
         if(is_hosted_fqdn(host)):
              hosts.add(host)
     return hosts


def main():
    states = [STATE_OK]
    messages = []

    prod_tree = get_tree("gridtype=on&gridtype_1=on&active=on&active_value=1&service=on&service_156=on&service_147=on")
    topology_hosts = set()
    for resourcegroup in prod_tree.findall("./ResourceGroup"):
        for resource, fqdn, services in get_ce_resources_with_fqdns_and_services(resourcegroup):
            if(is_hosted_fqdn(fqdn)):
                topology_hosts.add(fqdn)
    
    OMD_ROOT = os.environ.get('OMD_ROOT')
    secret_filepath = OMD_ROOT + "/var/check_mk/web/automation/automation.secret"
    access = open(secret_filepath,'r')
    secret_line = access.readlines()[0][:-1]
    action = "action=get_all_hosts"
    password = action + "&_username=automation&_secret=" + secret_line
    monitoring_hosts = get_monitoring_hosts(password)

    topology_diff = topology_hosts.difference(monitoring_hosts)
    
    if(len(topology_diff) > 0):
         states.append(STATE_CRITICAL)
 
    messages.append("Hosts in topology and not in monitoring: ")
    if topology_diff:
        messages.append(",".join(topology_diff))
    else:
        messages.append("None")
    messages.append("\n| count = %d" % len(topology_diff))
    print("".join(messages)) 
    sys.exit(max(states))

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        print("Exception occcurred when running probe: %s" % str(exc))
        sys.exit(STATE_CRITICAL)
