#!/usr/bin/env python3

import subprocess
import os
import sys
from os.path import exists
import traceback


STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3
out_messages = []
def executeCommandBD(com,host):
        with open('/tmp/out_shovler_proc_status'+host+'.txt','w+') as fout:
                with open('/tmp/err_shovler_proc_status'+host+'.txt','w+') as ferr:
                        #print(com)
                        out=subprocess.call([com],stdout=fout,stderr=ferr,timeout=500,shell=True)
                        fout.seek(0)
                        output=fout.read()
                        ferr.seek(0)
                        errors = ferr.read()
                        return output

def checkOuput(data):
        try:
                lines = data.splitlines()
                for l in lines:
                        if (isinstance(l,str) == True ):
                                if(len(l) > 1):
                                        if(l[0] != '#' and l.find("shoveler_packets_received") != -1 ):
                                              data = l.split(' ')
                                              qsize = int(float(data[1]))
                                              print ("shoveler_packets_received = %d" % qsize)
                                              return qsize  
                return STATE_CRITICAL
        except Exception as e:
                print (e)
                return STATE_CRITICAL
try:
        host = sys.argv[1]
        delta = 5;
        tmpCountFile = "/tmp/"+host+"provShoveler";
        e = executeCommandBD("curl -i http://"+host+":9667/metrics",host)
        #print(checkOuput(e))
        procp = checkOuput(e)
        if(procp == STATE_CRITICAL):
                sys.exit(procp)
        else:
               file_exists = exists(tmpCountFile)
               if(file_exists):
                      f = open(tmpCountFile, "r+")
                      oldprocsize = int(float(f.read()))
                      f.seek(0)
                      f.truncate(0) 
                      print(str(procp)+"  "+str(oldprocsize))
                      f.write(str(procp));
                      f.close()
                      if(abs(procp - oldprocsize) < delta):
                              procp = STATE_CRITICAL;
                      else:
                              procp = STATE_OK;
               else:
                      f = open(tmpCountFile, "w")
                      f.write(str(procp));
                      f.close()
                      procp = STATE_WARNING;

except Exception as e:
        os.remove(tmpCountFile)
        print (e)
        procp = STATE_CRITICAL
        traceback.print_exc() 
print(procp)
sys.exit(procp) 
