#!/usr/bin/env python3
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse
import sys
import os
import time

# Nagios exit status
STATE_OK = 0
STATE_WARNING = 1
STATE_CRITICAL = 2
STATE_UNKNOWN = 3

def main():
    args = parse_args()
    states = [STATE_OK]
    messages = []
    jobs = []
    extra_vars = {}
    if args.extra_vars:
        try:
            #parse extra condor configs to overwrite default:
            #example args from command like: --extra-vars _condor_VAR1=value1;_condor_VAR2=value2
            #parsed to dictionary extra_vars = {'_condor_VAR1' : value1, '_condor_VAR2' : value2}
            extra_vars = dict((k.strip(), v.strip())
                             for k, v in (element.split('=')
                                 for element in args.extra_vars.split(';')))

            for var in extra_vars.keys():
                if var.startswith('_condor_'):
                    os.environ[var] = str(extra_vars[var])
                    #print (var + os.environ[var])
                else:
                    messages.append("Extra variable not valid, should start with \'_condor_\', ignoring")
        except Exception as e:
            states.append(STATE_UNKNOWN)
            messages.append(str(e) + " Please review --extra-vars option")
            print (messages)

    #import htcondor after os.environ changed
    import htcondor

    try:
        coll = htcondor.Collector(args.collector)
        schedd_ad = coll.query(ad_type=htcondor.AdTypes.Schedd, constraint='Machine == "{}"'.format(args.schedd))[0]
        #print (schedd_ad)
        schedd = htcondor.Schedd(schedd_ad)
    except IOError as e:
        # Connection failed
        states.append(STATE_CRITICAL)
        messages.append(str(e))
    except Exception as e:
        # Other error
        states.append(STATE_UNKNOWN)
        messages.append(str(e))


    if args.mode == 'jobs':
        states.append(STATE_OK)
        messages.append('{} jobs running'.format(schedd_ad['TotalRunningJobs']))
        if (schedd_ad['TotalHeldJobs'] > 10000):
            states.append(STATE_WARNING)
            messages.append('{} held jobs'.format(schedd_ad['TotalHeldJobs']))

    elif args.mode == 'transfers':
        # sometimes the transfer queue attributes are missing
        if 'TransferQueueNumUploading' not in schedd_ad or \
           'TransferQueueNumDownloading' not in schedd_ad or \
           'TransferQueueNumWaitingToUpload' not in schedd_ad or \
           'TransferQueueNumWaitingToDownload' not in schedd_ad:
            states.append(STATE_WARNING)
            messages.append('schedd ad is missing transfer queue attributes')
        else:
            states.append(STATE_OK)
            messages.append('{} up, {} down'.format(
                schedd_ad['TransferQueueNumUploading'],
                schedd_ad['TransferQueueNumDownloading']))
            if schedd_ad['TransferQueueNumWaitingToUpload'] > 0:
                states.append(STATE_WARNING)
                messages.append('{} up waiting'.format(schedd_ad['TransferQueueNumWaitingToUpload']))
            if schedd_ad['TransferQueueNumWaitingToDownload'] > 0:
                states.append(STATE_WARNING)
                messages.append('{} down waiting'.format(schedd_ad['TransferQueueNumWaitingToDownload']))

    else:
        # default mode - check deamon stats
        if schedd_ad['DaemonStartTime'] + 3600 > time.time():
            states.append(STATE_WARNING)
            messages.append('Schedd recently restarted')
        if schedd_ad['RecentDaemonCoreDutyCycle'] >= .990:
            states.append(STATE_WARNING)
            messages.append('RecentDaemonCoreDutyCycle is {:.0f}%'.format(schedd_ad['RecentDaemonCoreDutyCycle'] * 100))

    state = max(states)
    message = ', '.join(messages) 
    if not message:
        message = 'Scheduler is up.'
    print(message)
    sys.exit(state)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', dest='mode', type=str,
                        help='Modes available: deamon,jobs,transfers')
    parser.add_argument('--collector', dest='collector', type=str,
                        help='Collector hostname for condor_q -pool')
    parser.add_argument('--schedd', dest='schedd', type=str,
                        help='Schedd hostname for condor_q -name')
    parser.add_argument('--extra-vars', dest='extra_vars', type=str,
                        help='Overwrite variables defined in condor_config_val, seperated by \';\', e.g. _condor_VAR1=value1;_condor_VAR2=value2')
    return parser.parse_args()

if __name__ == "__main__":
    # Run script as main
    main()
